# Generated by Django 5.2.4 on 2025-07-28 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('bound_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(default='not connected', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_account', models.CharField(max_length=15)),
                ('expired_package', models.CharField(max_length=255)),
                ('expired_voucher', models.CharField(max_length=255)),
                ('expiry_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_mac', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idA', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=17)),
                ('radius', models.CharField(max_length=50)),
                ('login_by', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=100)),
                ('uptime', models.CharField(max_length=50)),
                ('idle_time', models.CharField(max_length=50)),
                ('bytes_in', models.CharField(max_length=50)),
                ('bytes_out', models.CharField(max_length=50)),
                ('packets_in', models.CharField(max_length=50)),
                ('packets_out', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='core_active_usernam_f9d8ea_idx'), models.Index(fields=['mac_address'], name='core_active_mac_add_1e1524_idx')],
            },
        ),
        migrations.CreateModel(
            name='alternateSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_no', models.CharField(max_length=15)),
                ('alternate_current_ip', models.GenericIPAddressField()),
                ('alternate_current_mac', models.CharField(max_length=17)),
                ('alternate_bound_mac', models.CharField(max_length=17)),
                ('alternate_status', models.CharField(max_length=20)),
                ('alternate_bound_ip', models.GenericIPAddressField(null=True)),
                ('alternate_active_voucher', models.CharField(blank=True, max_length=50, null=True)),
                ('alternate_voucher_expiry', models.CharField(blank=True, max_length=50, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('session_timeout', models.DurationField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['alternate_no'], name='core_altern_alterna_08805f_idx'), models.Index(fields=['alternate_bound_mac'], name='core_altern_alterna_eabf04_idx')],
            },
        ),
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='core_announ_is_acti_293c4d_idx'), models.Index(fields=['priority'], name='core_announ_priorit_15a089_idx')],
            },
        ),
        migrations.CreateModel(
            name='AvailableVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255, null=True)),
                ('package_desc', models.CharField(max_length=50)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'indexes': [models.Index(fields=['voucher_code'], name='core_availa_voucher_9cc72d_idx'), models.Index(fields=['package'], name='core_availa_package_11616a_idx'), models.Index(fields=['package_desc'], name='core_availa_package_f2ade1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15, unique=True)),
                ('current_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('active_voucher', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('bound_ip', models.CharField(blank=True, max_length=15, null=True)),
                ('voucher_expiry', models.DateTimeField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=17, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clienth', to=settings.AUTH_USER_MODEL)),
                ('mac_addresses', models.ManyToManyField(blank=True, related_name='clients', to='core.clientmac')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_desc', models.CharField(max_length=255)),
                ('package_duration', models.DurationField(blank=True, null=True)),
                ('devices', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['package'], name='core_dailyp_package_401e3c_idx'), models.Index(fields=['package_desc'], name='core_dailyp_package_ca9222_idx')],
            },
        ),
        migrations.CreateModel(
            name='DHCPLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idD', models.CharField(max_length=50)),
                ('address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('dhcp_client_id', models.CharField(max_length=50, null=True)),
                ('address_lists', models.TextField(blank=True)),
                ('server', models.CharField(max_length=50)),
                ('dhcp_option', models.TextField(blank=True)),
                ('status', models.CharField(max_length=20)),
                ('expires_after', models.CharField(max_length=20)),
                ('last_seen', models.CharField(max_length=20)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('active_address', models.GenericIPAddressField()),
                ('active_mac_address', models.CharField(max_length=17)),
                ('active_client_id', models.CharField(max_length=50, null=True)),
                ('active_server', models.CharField(max_length=50)),
                ('host_name', models.CharField(blank=True, max_length=50, null=True)),
                ('radius', models.CharField(blank=True, max_length=50)),
                ('dynamic', models.CharField(blank=True, max_length=50)),
                ('blocked', models.CharField(blank=True, max_length=50)),
                ('disabled', models.CharField(blank=True, max_length=50)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='core.clienth')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchVoucher',
            fields=[
                ('dispatch_id', models.AutoField(primary_key=True, serialize=False)),
                ('dispatch_account', models.CharField(max_length=15)),
                ('dispatch_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispatch_package_desc', models.CharField(max_length=255)),
                ('dispatch_package', models.CharField(max_length=255)),
                ('dispatch_status', models.CharField(max_length=20)),
                ('dispatch_voucher_code', models.CharField(max_length=255)),
                ('dispatch_package_duration', models.DurationField(null=True)),
                ('dispatch_devices', models.CharField(max_length=20, null=True)),
                ('dispatch_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('dispatch_expiry', models.DateTimeField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dispatch_account'], name='core_dispat_dispatc_58aab2_idx'), models.Index(fields=['dispatch_voucher_code'], name='core_dispat_dispatc_ff8c90_idx'), models.Index(fields=['dispatch_status'], name='core_dispat_dispatc_924dba_idx'), models.Index(fields=['dispatch_expiry'], name='core_dispat_dispatc_ed42b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('network', 'Network Infrastructure'), ('maintenance', 'Maintenance & Repairs'), ('labor', 'Labor & Salaries'), ('marketing', 'Marketing & Advertising'), ('office', 'Office Expenses'), ('utility', 'Utilities'), ('software', 'Software & Licensing'), ('other', 'Other')], default='other', max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expense_date'], name='core_expens_expense_9af794_idx'), models.Index(fields=['category'], name='core_expens_categor_358de0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=255)),
                ('investment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investment_type', models.CharField(choices=[('seed', 'Seed Funding'), ('angel', 'Angel Investment'), ('vc', 'Venture Capital'), ('other', 'Other')], default='other', max_length=20)),
                ('equity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['investment_type'], name='core_invest_investm_79a00a_idx'), models.Index(fields=['investment_date'], name='core_invest_investm_ccbf2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_desc', models.CharField(max_length=255)),
                ('package_duration', models.DurationField(blank=True, null=True)),
                ('devices', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['package'], name='core_packag_package_8e9ecc_idx'), models.Index(fields=['package_desc'], name='core_packag_package_4c90d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=255)),
                ('initiator', models.CharField(max_length=25)),
                ('checkout_request_id', models.CharField(max_length=255, null=True)),
                ('package_desc', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('queue_time', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=25)),
                ('used_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient'], name='core_queue_recipie_404e7b_idx'), models.Index(fields=['checkout_request_id'], name='core_queue_checkou_53cc35_idx'), models.Index(fields=['status'], name='core_queue_status_adc20b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('participants', models.ManyToManyField(blank=True, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('initiator', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('date', models.CharField(max_length=255, null=True)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.CharField(max_length=255)),
                ('merchant_request_id', models.CharField(max_length=255)),
                ('checkout_request_id', models.CharField(max_length=255)),
                ('transaction_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['transaction_id'], name='core_transa_transac_665709_idx'), models.Index(fields=['initiator'], name='core_transa_initiat_5a4340_idx'), models.Index(fields=['checkout_request_id'], name='core_transa_checkou_eff89c_idx'), models.Index(fields=['merchant_request_id'], name='core_transa_merchan_b92c63_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='clienth',
            index=models.Index(fields=['status'], name='core_client_status_ef0095_idx'),
        ),
        migrations.AddIndex(
            model_name='clienth',
            index=models.Index(fields=['voucher_expiry'], name='core_client_voucher_b122ae_idx'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['mac_address'], name='core_dhcple_mac_add_2f9951_idx'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['active_mac_address'], name='core_dhcple_active__8961b5_idx'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['active_address'], name='core_dhcple_active__859a08_idx'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['client'], name='core_dhcple_client__f18129_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room'], name='core_messag_room_id_70ddbb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['time'], name='core_messag_time_9f6908_idx'),
        ),
    ]
