# Generated by Django 5.2.4 on 2025-08-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clienth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchvoucher',
            name='active_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispatchvoucher',
            name='total_download',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatchvoucher',
            name='total_upload',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatchvoucher',
            name='uptime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatchvoucher',
            name='usermanid',
            field=models.CharField(blank=True, null=True),
        ),
    ]
