#docker compose for v3 isolation from v2 stable
services:
  webv3:
    build:
      context: .
    container_name: teralinkx_webv3

    # IMPORTANT: bind to port 8009
    command: gunicorn --config gunicorn_config.py teralinkx.wsgi:application

    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles

    ports:
      - "8009:8009"

    env_file:
      - .env

    restart: always

    networks:
      - app_network

  # ===============================
  # FREERADIUS SERVER
  # ===============================
  freeradius:
    image: freeradius/freeradius-server:latest
    container_name: freeradius_server
    ports:
      - "1812:1812/udp"  # Authentication
      - "1813:1813/udp"  # Accounting
      - "3799:3799/udp"  # CoA (Change of Authorization)
    volumes:
      - ./freeradius/mods-available:/etc/freeradius/mods-available
      - ./freeradius/mods-enabled:/etc/freeradius/mods-enabled
      - ./freeradius/sites-available:/etc/freeradius/sites-available
      - ./freeradius/sites-enabled:/etc/freeradius/sites-enabled
      - ./freeradius/clients.conf:/etc/freeradius/clients.conf
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=radius
      - DB_USER=radius
      - DB_PASS=radiuspass
    restart: always
    networks:
      - app_network

networks:
  app_network:
    external: true
    name: teralinkx_app_network
