# Generated by Django 5.2.4 on 2025-11-07 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_sync_interval', models.IntegerField(default=5, help_text='Voucher sync interval in minutes')),
                ('user_sync_interval', models.IntegerField(default=10, help_text='User sync interval in minutes')),
                ('session_sync_interval', models.IntegerField(default=2, help_text='Session sync interval in minutes')),
                ('transaction_sync_interval', models.IntegerField(default=15, help_text='Transaction sync interval in minutes')),
                ('keep_sync_logs_days', models.IntegerField(default=30, help_text='Days to keep sync logs')),
                ('max_sync_retries', models.IntegerField(default=3, help_text='Maximum sync retry attempts')),
                ('max_sync_size_mb', models.IntegerField(default=50, help_text='Maximum sync payload size in MB')),
                ('sync_batch_size', models.IntegerField(default=100, help_text='Records per sync batch')),
                ('sync_endpoint', models.URLField(help_text='Central server sync endpoint')),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication', max_length=255)),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Sync request timeout')),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('compression_enabled', models.BooleanField(default=True)),
                ('encryption_enabled', models.BooleanField(default=True)),
                ('conflict_resolution', models.CharField(choices=[('central_wins', 'Central Wins'), ('local_wins', 'Local Wins'), ('newer_wins', 'Newer Wins'), ('manual', 'Manual Resolution')], default='newer_wins', max_length=20)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_config', to='locations.location')),
            ],
            options={
                'verbose_name': 'Sync Configuration',
                'verbose_name_plural': 'Sync Configurations',
            },
        ),
        migrations.CreateModel(
            name='DataChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_type', models.CharField(choices=[('voucher', 'Voucher'), ('user', 'User'), ('session', 'Session'), ('transaction', 'Transaction'), ('device', 'Device'), ('package', 'Package')], max_length=20)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('object_id', models.CharField(help_text='ID of the changed object', max_length=100)),
                ('old_data', models.JSONField(blank=True, help_text='Data before change', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='Data after change', null=True)),
                ('changed_fields', models.JSONField(default=list, help_text='List of changed field names')),
                ('is_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('change_reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_changes', to='locations.location')),
            ],
            options={
                'verbose_name': 'Data Change Log',
                'verbose_name_plural': 'Data Change Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location', 'is_synced'], name='sync_datach_locatio_480628_idx'), models.Index(fields=['model_type', 'change_type'], name='sync_datach_model_t_2a8a3d_idx'), models.Index(fields=['created_at'], name='sync_datach_created_65b2d7_idx'), models.Index(fields=['is_synced'], name='sync_datach_is_sync_904428_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_type', models.CharField(choices=[('vouchers', 'Vouchers'), ('users', 'Users'), ('sessions', 'Sessions'), ('transactions', 'Transactions'), ('packages', 'Packages'), ('devices', 'Devices'), ('network_config', 'Network Configuration'), ('full', 'Full Sync')], max_length=20)),
                ('sync_direction', models.CharField(choices=[('upload', 'Upload to Central'), ('download', 'Download from Central'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_synced', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('checksum', models.CharField(blank=True, help_text='Data integrity checksum', max_length=64)),
                ('data_version', models.CharField(blank=True, help_text='Data version identifier', max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('error_details', models.JSONField(default=dict, help_text='Detailed error information')),
                ('is_manual', models.BooleanField(default=False)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_syncs', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='locations.location')),
            ],
            options={
                'verbose_name': 'Location Sync Log',
                'verbose_name_plural': 'Location Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['location', 'started_at'], name='sync_locati_locatio_c84960_idx'), models.Index(fields=['sync_type'], name='sync_locati_sync_ty_221def_idx'), models.Index(fields=['status'], name='sync_locati_status_3d21a4_idx'), models.Index(fields=['started_at'], name='sync_locati_started_3bad34_idx'), models.Index(fields=['completed_at'], name='sync_locati_complet_404ff3_idx')],
            },
        ),
    ]
