# Generated by Django 5.2.4 on 2026-01-27 11:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('packages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('is_roaming', models.BooleanField(default=False)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.GenericIPAddressField()),
                ('nas_ip_address', models.GenericIPAddressField()),
                ('nas_identifier', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('uptime', models.DurationField(default=datetime.timedelta(0))),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('download_speed_bps', models.BigIntegerField(default=0)),
                ('upload_speed_bps', models.BigIntegerField(default=0)),
                ('packet_loss', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('latency_ms', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_authenticated', models.BooleanField(default=True)),
                ('terminate_cause', models.CharField(blank=True, max_length=50)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, help_text='Device associated with this active session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_active_sessions', to='users.userdevice')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_active_sessions', to='users.clienth')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.dispatchvoucher')),
            ],
            options={
                'verbose_name': 'Active Session',
                'verbose_name_plural': 'Active Sessions',
            },
        ),
        migrations.CreateModel(
            name='DataUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_roaming', models.BooleanField(default=False)),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('total_packets', models.BigIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('usage_type', models.CharField(choices=[('web', 'Web Browsing'), ('streaming', 'Video Streaming'), ('gaming', 'Online Gaming'), ('download', 'File Download'), ('upload', 'File Upload'), ('voip', 'VoIP/Voice Call'), ('other', 'Other')], default='other', max_length=20)),
                ('protocol', models.CharField(blank=True, help_text='TCP/UDP/ICMP etc.', max_length=20)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('average_speed_bps', models.BigIntegerField(default=0)),
                ('peak_speed_bps', models.BigIntegerField(default=0)),
                ('packet_loss_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('latency_ms', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost_per_mb', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_domain', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userdevice')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.activesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_usage_records', to='users.clienth')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.dispatchvoucher')),
            ],
            options={
                'verbose_name': 'Data Usage Record',
                'verbose_name_plural': 'Data Usage Records',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DHCPLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idD', models.CharField(max_length=50)),
                ('address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('dhcp_client_id', models.CharField(max_length=50, null=True)),
                ('address_lists', models.TextField(blank=True)),
                ('server', models.CharField(max_length=50)),
                ('dhcp_option', models.TextField(blank=True)),
                ('status', models.CharField(max_length=20)),
                ('expires_after', models.DurationField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('age', models.DurationField(blank=True, null=True)),
                ('active_address', models.GenericIPAddressField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='users.clienth')),
            ],
            options={
                'verbose_name': 'DHCP Lease',
                'verbose_name_plural': 'DHCP Leases',
            },
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['session_id'], name='analytics_a_session_afd181_idx'),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['user', 'start_time'], name='analytics_a_user_id_a67353_idx'),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['mac_address'], name='analytics_a_mac_add_bf2054_idx'),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['location'], name='analytics_a_locatio_6b6bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['is_authenticated'], name='analytics_a_is_auth_7085b3_idx'),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['start_time'], name='analytics_a_start_t_aa5fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['device'], name='analytics_a_device__520800_idx'),
        ),
        migrations.AddIndex(
            model_name='datausagerecord',
            index=models.Index(fields=['user', 'start_time'], name='analytics_d_user_id_e067a5_idx'),
        ),
        migrations.AddIndex(
            model_name='datausagerecord',
            index=models.Index(fields=['device', 'start_time'], name='analytics_d_device__c5853b_idx'),
        ),
        migrations.AddIndex(
            model_name='datausagerecord',
            index=models.Index(fields=['voucher', 'start_time'], name='analytics_d_voucher_e70f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='datausagerecord',
            index=models.Index(fields=['location', 'start_time'], name='analytics_d_locatio_50846b_idx'),
        ),
        migrations.AddIndex(
            model_name='datausagerecord',
            index=models.Index(fields=['usage_type'], name='analytics_d_usage_t_540496_idx'),
        ),
        migrations.AddIndex(
            model_name='datausagerecord',
            index=models.Index(fields=['start_time'], name='analytics_d_start_t_f09261_idx'),
        ),
    ]
