# Generated by Django 5.2.4 on 2025-11-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('locations', '0001_initial'),
        ('packages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhcplease',
            options={'verbose_name': 'DHCP Lease', 'verbose_name_plural': 'DHCP Leases'},
        ),
        migrations.AddField(
            model_name='activesession',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Device associated with this active session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to='users.userdevice'),
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='active_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['device'], name='analytics_a_device__520800_idx'),
        ),
    ]
