# Generated by Django 5.2.12 on 2026-04-18 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('affected_area', models.CharField(blank=True, max_length=200)),
                ('reported_by', models.CharField(blank=True, max_length=100)),
                ('outage_event_id', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RefundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(db_index=True, max_length=100)),
                ('client_username', models.CharField(blank=True, max_length=150)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('downtime_minutes', models.IntegerField(default=0)),
                ('refund_type', models.CharField(choices=[('individual', 'Individual'), ('batch', 'Batch'), ('sla', 'SLA Credit')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('downtime_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='analytics.downtimerecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
