# Generated by Django 5.2.4 on 2026-02-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nasname', models.TextField()),
                ('shortname', models.TextField()),
                ('type', models.TextField(default='other')),
                ('ports', models.IntegerField(blank=True, null=True)),
                ('secret', models.TextField()),
                ('server', models.TextField(blank=True, null=True)),
                ('community', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NasReload',
            fields=[
                ('nasipaddress', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('reloadtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'nasreload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadAcct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.TextField()),
                ('acctuniqueid', models.TextField(unique=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('realm', models.TextField(blank=True, null=True)),
                ('nasipaddress', models.GenericIPAddressField()),
                ('nasportid', models.TextField(blank=True, null=True)),
                ('nasporttype', models.TextField(blank=True, null=True)),
                ('acctstarttime', models.DateTimeField(blank=True, null=True)),
                ('acctupdatetime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctinterval', models.BigIntegerField(blank=True, null=True)),
                ('acctsessiontime', models.BigIntegerField(blank=True, null=True)),
                ('acctauthentic', models.TextField(blank=True, null=True)),
                ('connectinfo_start', models.TextField(blank=True, null=True)),
                ('connectinfo_stop', models.TextField(blank=True, null=True)),
                ('acctinputoctets', models.BigIntegerField(blank=True, null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, null=True)),
                ('calledstationid', models.TextField(blank=True, null=True)),
                ('callingstationid', models.TextField(blank=True, null=True)),
                ('acctterminatecause', models.TextField(blank=True, null=True)),
                ('servicetype', models.TextField(blank=True, null=True)),
                ('framedprotocol', models.TextField(blank=True, null=True)),
                ('framedipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('framedipv6address', models.GenericIPAddressField(blank=True, null=True)),
                ('framedipv6prefix', models.GenericIPAddressField(blank=True, null=True)),
                ('framedinterfaceid', models.TextField(blank=True, null=True)),
                ('delegatedipv6prefix', models.GenericIPAddressField(blank=True, null=True)),
                ('class_field', models.TextField(blank=True, db_column='class', null=True)),
            ],
            options={
                'db_table': 'radacct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(default='')),
                ('attribute', models.TextField(default='')),
                ('op', models.CharField(default='==', max_length=2)),
                ('value', models.TextField(default='')),
            ],
            options={
                'db_table': 'radcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadGroupCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.TextField(default='')),
                ('attribute', models.TextField(default='')),
                ('op', models.CharField(default='==', max_length=2)),
                ('value', models.TextField(default='')),
            ],
            options={
                'db_table': 'radgroupcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadGroupReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.TextField(default='')),
                ('attribute', models.TextField(default='')),
                ('op', models.CharField(default='=', max_length=2)),
                ('value', models.TextField(default='')),
            ],
            options={
                'db_table': 'radgroupreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadPostAuth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('pass_field', models.TextField(blank=True, db_column='pass', null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('calledstationid', models.TextField(blank=True, null=True)),
                ('callingstationid', models.TextField(blank=True, null=True)),
                ('authdate', models.DateTimeField(auto_now_add=True)),
                ('class_field', models.TextField(blank=True, db_column='class', null=True)),
            ],
            options={
                'db_table': 'radpostauth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(default='')),
                ('attribute', models.TextField(default='')),
                ('op', models.CharField(default='=', max_length=2)),
                ('value', models.TextField(default='')),
            ],
            options={
                'db_table': 'radreply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadUserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(default='')),
                ('groupname', models.TextField(default='')),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'radusergroup',
                'managed': False,
            },
        ),
    ]
