# Generated by Django 5.2.4 on 2026-02-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('profile', models.CharField(max_length=255)),
                ('duration_seconds', models.IntegerField(help_text='Voucher validity in seconds')),
                ('activated_at', models.DateTimeField(blank=True, help_text='First login time', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiry time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vouchers',
            },
        ),
    ]
