# Generated by Django 5.2.4 on 2025-11-07 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('time_based', 'Time-Based'), ('data_based', 'Data-Based'), ('unlimited', 'Unlimited'), ('hybrid', 'Hybrid'), ('corporate', 'Corporate')], default='time_based', max_length=20)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.DurationField(help_text='Package validity duration')),
                ('speed_limit_mbps', models.IntegerField(help_text='Maximum speed in Mbps')),
                ('data_limit_mb', models.BigIntegerField(blank=True, help_text='Data limit in MB (null = unlimited)', null=True)),
                ('device_limit', models.IntegerField(default=1)),
                ('qos_priority', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('business', 'Business'), ('real_time', 'Real-time')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('allow_roaming', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('radius_group', models.CharField(blank=True, max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('color_code', models.CharField(default='#007bff', max_length=7)),
                ('tags', models.JSONField(default=list, help_text='Tags for filtering and search')),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('sold_quantity', models.IntegerField(default=0)),
                ('locations', models.ManyToManyField(blank=True, to='locations.location')),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['display_order', 'tier', 'price'],
            },
        ),
        migrations.CreateModel(
            name='DispatchVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('session_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('exhausted', 'Data Exhausted'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('allowed_mac_addresses', models.JSONField(default=list, help_text='List of allowed MAC addresses')),
                ('concurrent_sessions', models.IntegerField(default=0)),
                ('is_roaming', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('home_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_dispatch_vouchers', to='locations.location')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_vouchers', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagetype')),
            ],
            options={
                'verbose_name': 'Dispatch Voucher',
                'verbose_name_plural': 'Dispatch Vouchers',
                'db_table': 'dispatch_vouchers',
            },
        ),
        migrations.CreateModel(
            name='AvailableVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_code', models.CharField(max_length=255, unique=True)),
                ('voucher_type', models.CharField(choices=[('pre_generated', 'Pre-generated'), ('bulk', 'Bulk Voucher'), ('promotional', 'Promotional')], default='pre_generated', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=100)),
                ('is_roaming', models.BooleanField(default=False)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_vouchers', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packagetype')),
            ],
            options={
                'verbose_name': 'Available Voucher',
                'verbose_name_plural': 'Available Vouchers',
                'db_table': 'available_vouchers',
            },
        ),
        migrations.AddIndex(
            model_name='packagetype',
            index=models.Index(fields=['category', 'tier'], name='packages_categor_df2c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='packagetype',
            index=models.Index(fields=['is_active', 'is_public'], name='packages_is_acti_193620_idx'),
        ),
        migrations.AddIndex(
            model_name='packagetype',
            index=models.Index(fields=['price'], name='packages_price_09c080_idx'),
        ),
        migrations.AddIndex(
            model_name='packagetype',
            index=models.Index(fields=['is_featured'], name='packages_is_feat_19db56_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchvoucher',
            index=models.Index(fields=['voucher_code'], name='dispatch_vo_voucher_1ed990_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchvoucher',
            index=models.Index(fields=['user', 'status'], name='dispatch_vo_user_id_8f6300_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchvoucher',
            index=models.Index(fields=['status'], name='dispatch_vo_status_73a800_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchvoucher',
            index=models.Index(fields=['expires_at'], name='dispatch_vo_expires_b2e10d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchvoucher',
            index=models.Index(fields=['activated_at'], name='dispatch_vo_activat_de5c15_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchvoucher',
            index=models.Index(fields=['is_roaming'], name='dispatch_vo_is_roam_fbbb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchvoucher',
            index=models.Index(fields=['transaction_id'], name='dispatch_vo_transac_8f23c4_idx'),
        ),
        migrations.AddIndex(
            model_name='availablevoucher',
            index=models.Index(fields=['voucher_code'], name='available_v_voucher_c38b73_idx'),
        ),
        migrations.AddIndex(
            model_name='availablevoucher',
            index=models.Index(fields=['is_used'], name='available_v_is_used_c60600_idx'),
        ),
        migrations.AddIndex(
            model_name='availablevoucher',
            index=models.Index(fields=['batch_id'], name='available_v_batch_i_742a67_idx'),
        ),
        migrations.AddIndex(
            model_name='availablevoucher',
            index=models.Index(fields=['location'], name='available_v_locatio_54598d_idx'),
        ),
        migrations.AddIndex(
            model_name='availablevoucher',
            index=models.Index(fields=['valid_until'], name='available_v_valid_u_a97708_idx'),
        ),
    ]
