# Generated by Django 5.2.4 on 2025-11-07 14:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISPEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Device hostname', max_length=100, unique=True)),
                ('equipment_type', models.CharField(choices=[('core_router', 'Core Router'), ('access_router', 'Access Router'), ('bras', 'BRAS/BNG'), ('olt', 'OLT'), ('switch', 'Switch'), ('wireless_ap', 'Wireless AP'), ('firewall', 'Firewall'), ('dns_server', 'DNS Server'), ('radius_server', 'RADIUS Server'), ('nms', 'Network Management Server')], max_length=20)),
                ('vendor', models.CharField(choices=[('mikrotik', 'MikroTik'), ('cisco', 'Cisco'), ('juniper', 'Juniper'), ('huawei', 'Huawei'), ('zte', 'ZTE'), ('ubiquiti', 'Ubiquiti'), ('cambium', 'Cambium'), ('mimosa', 'Mimosa'), ('ruckus', 'Ruckus'), ('other', 'Other')], max_length=20)),
                ('model', models.CharField(help_text='Model name', max_length=100)),
                ('management_ip', models.GenericIPAddressField(help_text='Management IP', unique=True)),
                ('public_ip', models.GenericIPAddressField(blank=True, help_text='Public facing IP', null=True)),
                ('ssh_port', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('api_port', models.IntegerField(default=8728, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('enable_password', models.CharField(blank=True, max_length=255)),
                ('rack_position', models.CharField(blank=True, help_text='e.g., RACK-1-U12', max_length=20)),
                ('role', models.CharField(choices=[('core', 'Core Network'), ('aggregation', 'Aggregation'), ('access', 'Access Network'), ('backhaul', 'Backhaul'), ('customer_facing', 'Customer Facing'), ('management', 'Management')], default='access', max_length=20)),
                ('status', models.CharField(choices=[('production', 'Production'), ('maintenance', 'Maintenance'), ('backup', 'Backup/Spare'), ('offline', 'Offline'), ('decommissioned', 'Decommissioned')], default='production', max_length=15)),
                ('max_capacity', models.IntegerField(default=0, help_text='Max user capacity')),
                ('current_users', models.IntegerField(default=0, help_text='Current active users')),
                ('uplink_speed', models.CharField(blank=True, help_text='e.g., 1G, 10G', max_length=20)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('pop', models.ForeignKey(help_text='Point of Presence', on_delete=django.db.models.deletion.CASCADE, related_name='network_equipment', to='locations.location')),
            ],
            options={
                'verbose_name': 'ISP Equipment',
                'verbose_name_plural': 'ISP Equipment',
                'ordering': ['pop', 'role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ISPEquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('config_backup', 'Configuration Backup'), ('config_change', 'Configuration Change'), ('firmware_update', 'Firmware Update'), ('maintenance', 'Maintenance'), ('reboot', 'Device Reboot'), ('troubleshoot', 'Troubleshooting'), ('user_sync', 'User Database Sync'), ('hotspot_config', 'Hotspot Configuration')], max_length=20)),
                ('description', models.TextField()),
                ('successful', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='security.ispequipment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ISP Equipment Log',
                'verbose_name_plural': 'ISP Equipment Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('login_success', 'Login Successful'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('two_factor_enabled', '2FA Enabled'), ('two_factor_disabled', '2FA Disabled'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('role_changed', 'Role Changed'), ('device_registered', 'Device Registered'), ('device_connected', 'Device Connected'), ('device_disconnected', 'Device Disconnected'), ('device_blocked', 'Device Blocked'), ('device_unblocked', 'Device Unblocked'), ('device_trusted', 'Device Trusted'), ('device_untrusted', 'Device Untrusted'), ('voucher_activated', 'Voucher Activated'), ('voucher_expired', 'Voucher Expired'), ('roaming_started', 'Roaming Started'), ('roaming_ended', 'Roaming Ended'), ('access_denied', 'Access Denied'), ('suspicious_activity', 'Suspicious Activity'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('refund_issued', 'Refund Issued'), ('balance_adjusted', 'Balance Adjusted'), ('system_startup', 'System Startup'), ('system_shutdown', 'System Shutdown'), ('configuration_change', 'Configuration Changed'), ('maintenance_mode', 'Maintenance Mode Toggled')], max_length=50)),
                ('action_category', models.CharField(choices=[('authentication', 'Authentication'), ('authorization', 'Authorization'), ('device_management', 'Device Management'), ('network_access', 'Network Access'), ('financial', 'Financial'), ('system', 'System Events'), ('compliance', 'Compliance')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('threat_score', models.IntegerField(default=0, help_text='0-100 threat score')),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_logs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='users.clienth')),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ispequipment',
            index=models.Index(fields=['pop', 'status'], name='security_is_pop_id_10105b_idx'),
        ),
        migrations.AddIndex(
            model_name='ispequipment',
            index=models.Index(fields=['equipment_type', 'role'], name='security_is_equipme_efbf20_idx'),
        ),
        migrations.AddIndex(
            model_name='ispequipment',
            index=models.Index(fields=['management_ip'], name='security_is_managem_156e50_idx'),
        ),
        migrations.AddIndex(
            model_name='ispequipment',
            index=models.Index(fields=['status'], name='security_is_status_33f3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['user', 'created_at'], name='security_se_user_id_003c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['action_type'], name='security_se_action__641e26_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['severity'], name='security_se_severit_3f6e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['is_suspicious'], name='security_se_is_susp_9c02c8_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['resolved'], name='security_se_resolve_5f1e15_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['created_at'], name='security_se_created_9513ba_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['correlation_id'], name='security_se_correla_3d770a_idx'),
        ),
    ]
