#!/bin/bash
# CICIDS2017/2018 PCAP Download Guide for TCP Replay Testing

echo "═══════════════════════════════════════════════════════════════"
echo "CICIDS PCAP FILES FOR HIDS TESTING"
echo "═══════════════════════════════════════════════════════════════"

# OPTION 1: CICIDS2017 Full Dataset (Original Source)
echo ""
echo "📦 OPTION 1: CICIDS2017 Full PCAP Files"
echo "Source: Canadian Institute for Cybersecurity"
echo "URL: https://www.unb.ca/cic/datasets/ids-2017.html"
echo ""
echo "Files Available:"
echo "  - Monday (Benign): ~11GB PCAP"
echo "  - Tuesday (FTP-Patator, SSH-Patator): ~12GB"
echo "  - Wednesday (DoS/DDoS): ~13GB"
echo "  - Thursday (Web Attack, Infiltration): ~9GB"
echo "  - Friday (Botnet, PortScan, DDoS): ~10GB"
echo ""
echo "Download Command:"
echo "  wget https://www.unb.ca/cic/datasets/ids-2017.html"
echo "  (Manual download required - registration needed)"
echo ""

# OPTION 2: CICIDS2018 (CSE-CIC-IDS2018)
echo "📦 OPTION 2: CICIDS2018 Full PCAP Files"
echo "Source: Canadian Institute for Cybersecurity"
echo "URL: https://www.unb.ca/cic/datasets/ids-2018.html"
echo ""
echo "Files Available:"
echo "  - Wednesday-14-02-2018 (Brute Force): ~8GB"
echo "  - Thursday-15-02-2018 (DoS/DDoS): ~10GB"
echo "  - Friday-16-02-2018 (DoS/DDoS): ~9GB"
echo "  - Friday-23-02-2018 (Brute Force, XSS, SQL Injection): ~7GB"
echo ""

# OPTION 3: Kaggle (Easier Access)
echo "📦 OPTION 3: Kaggle Datasets (Easier)"
echo "URL: https://www.kaggle.com/datasets/cicdataset/cicids2017"
echo ""
echo "Install Kaggle CLI:"
echo "  pip install kaggle"
echo "  kaggle datasets download -d cicdataset/cicids2017"
echo ""

# OPTION 4: AWS S3 (If Available)
echo "📦 OPTION 4: Research Repositories"
echo "Some universities mirror the dataset:"
echo "  - Check your institution's research data repository"
echo "  - Contact CIC directly: cic@unb.ca"
echo ""

# BEST FOR TESTING: Friday Attack Files
echo "═══════════════════════════════════════════════════════════════"
echo "🎯 RECOMMENDED FOR TESTING: Friday Attack Files"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "CICIDS2017 Friday (Best for testing):"
echo "  - Contains: Botnet, PortScan, DDoS attacks"
echo "  - File: Friday-WorkingHours.pcap (~10GB)"
echo "  - Attacks: ARES Botnet, PortScan, DDoS LOIT"
echo ""
echo "CICIDS2018 Friday-23-02-2018 (Web attacks):"
echo "  - Contains: Brute Force, XSS, SQL Injection"
echo "  - File: Friday-23-02-2018.pcap (~7GB)"
echo "  - Perfect for testing web attack detection"
echo ""

# ALTERNATIVE: Smaller Sample PCAPs
echo "═══════════════════════════════════════════════════════════════"
echo "💡 ALTERNATIVE: Smaller Sample Files"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "If full datasets are too large, use these:"
echo ""
echo "1. DARPA/MIT Lincoln Lab (Classic):"
echo "   wget https://www.ll.mit.edu/r-d/datasets/1998-darpa-intrusion-detection-evaluation-dataset"
echo ""
echo "2. UNSW-NB15 (Smaller, Modern):"
echo "   https://research.unsw.edu.au/projects/unsw-nb15-dataset"
echo ""
echo "3. Create Your Own Attack Traffic:"
echo "   - Use Metasploit to generate attacks"
echo "   - Capture with tcpdump/Wireshark"
echo "   - Replay with tcpreplay"
echo ""

# TCP REPLAY COMMANDS
echo "═══════════════════════════════════════════════════════════════"
echo "🔄 TCP REPLAY COMMANDS FOR TESTING"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Install tcpreplay:"
echo "   sudo apt install tcpreplay"
echo ""
echo "2. Replay at normal speed:"
echo "   sudo tcpreplay -i br-c51890515ece Friday-WorkingHours.pcap"
echo ""
echo "3. Replay at 10x speed:"
echo "   sudo tcpreplay -i br-c51890515ece -t Friday-WorkingHours.pcap"
echo ""
echo "4. Replay specific time range:"
echo "   sudo tcpreplay -i br-c51890515ece --duration=300 Friday-WorkingHours.pcap"
echo ""
echo "5. Loop replay (continuous testing):"
echo "   sudo tcpreplay -i br-c51890515ece --loop=10 Friday-WorkingHours.pcap"
echo ""
echo "6. Monitor HIDS while replaying:"
echo "   # Terminal 1:"
echo "   sudo tcpreplay -i br-c51890515ece Friday-WorkingHours.pcap"
echo ""
echo "   # Terminal 2:"
echo "   docker logs -f hids_engine"
echo ""
echo "   # Terminal 3:"
echo "   watch -n 1 'curl -s http://localhost:9090/api/v1/query?query=hids_ml_predictions_total'"
echo ""

# DIRECT DOWNLOAD LINKS (If Available)
echo "═══════════════════════════════════════════════════════════════"
echo "📥 DIRECT DOWNLOAD ATTEMPTS"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Try these direct links (may require authentication):"
echo ""
echo "# CICIDS2017 Friday (Botnet + PortScan)"
echo "wget --user-agent='Mozilla/5.0' \\"
echo "  'https://iscxdownloads.cs.unb.ca/iscxdownloads/CIC-IDS-2017/PCAPs/Friday-WorkingHours.pcap'"
echo ""
echo "# CICIDS2018 Friday-23 (Web Attacks)"
echo "wget --user-agent='Mozilla/5.0' \\"
echo "  'https://iscxdownloads.cs.unb.ca/iscxdownloads/CSE-CIC-IDS2018/Processed%20Traffic%20Data%20for%20ML%20Algorithms/Friday-23-02-2018_TrafficForML_CICFlowMeter.csv'"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✅ SETUP COMPLETE"
echo "═══════════════════════════════════════════════════════════════"
