# Generated by Django 5.2.4 on 2026-02-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuestream',
            name='category',
            field=models.CharField(choices=[('voucher_sales', 'Voucher Sales'), ('package_sales', 'Package Sales'), ('usage_charges', 'Usage Charges'), ('premium_services', 'Premium Services'), ('ads_revenue', 'Advertising Revenue'), ('value_added', 'Value Added Services'), ('other', 'Other Revenue')], max_length=50),
        ),
    ]
