# Generated by Django 5.2.4 on 2026-03-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_revenuestream_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='result_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='result_desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
