# Generated by Django 5.2.4 on 2026-03-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_paymenttransaction_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='completed', max_length=20),
        ),
    ]
