# Generated by Django 5.2.4 on 2026-03-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('mixed', 'M-Pesa + Balance'), ('balance', 'Account Balance'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('card_visa', 'Visa Card'), ('card_mastercard', 'MasterCard'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='mpesa', max_length=20),
        ),
    ]
