# Generated by Django 5.2.4 on 2026-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('mpesa+balance', 'M-Pesa + Balance'), ('balance', 'Account Balance'), ('stripe', 'Stripe'), ('stripe+balance', 'Stripe + Balance'), ('card_visa', 'Visa Card'), ('card_visa+balance', 'Visa Card + Balance'), ('card_mastercard', 'MasterCard'), ('card_mastercard+balance', 'MasterCard + Balance'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('paypal', 'PayPal')], default='mpesa', max_length=30),
        ),
    ]
