# Generated by Django 5.2.4 on 2026-03-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_update_callback_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='callback_url',
            field=models.URLField(blank=True, default='https://srv.teralinkxwaves.uk/api/payments/callback/', help_text="System's callback URL for payment notifications. This is where payment gateways will send transaction updates."),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='webhook_url',
            field=models.URLField(blank=True, default='https://srv.teralinkxwaves.uk/api/webhooks/payment/', help_text='Webhook URL for real-time payment events (for supported gateways like Stripe)'),
        ),
    ]
