# Generated by Django 5.2.12 on 2026-04-09 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_paymentgateway_callback_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('forecasting', 'Time Series Forecasting')], max_length=50)),
                ('use_case', models.CharField(choices=[('churn_prediction', 'Churn Prediction'), ('fraud_detection', 'Fraud Detection'), ('cash_flow_forecast', 'Cash Flow Forecasting')], max_length=50)),
                ('model_file_path', models.CharField(max_length=500)),
                ('accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('auc_roc', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('training_data_size', models.IntegerField(blank=True, null=True)),
                ('training_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('training', 'Training'), ('testing', 'Testing'), ('active', 'Active'), ('inactive', 'Inactive')], default='training', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('fallback_strategy', models.CharField(choices=[('rule_based', 'Rule-Based Model'), ('previous_version', 'Previous Model Version'), ('none', 'No Fallback')], default='rule_based', max_length=50)),
                ('prediction_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('fallback_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.mlmodel')),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-created_at'],
            },
        ),
    ]
