# Generated by Django 5.2.12 on 2026-04-09 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_mlmodel'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('churn_score', models.FloatField(help_text='Churn probability (0-1)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('prediction_method', models.CharField(choices=[('rule_based', 'Rule-Based Model'), ('ml_model', 'Machine Learning Model'), ('hybrid', 'Hybrid (Rule + ML)')], default='rule_based', max_length=20)),
                ('risk_factors', models.JSONField(default=dict, help_text='Contributing factors with scores')),
                ('top_factors', models.JSONField(default=list, help_text='Top 3 factors driving churn risk')),
                ('days_since_last_session', models.IntegerField(blank=True, null=True)),
                ('support_tickets_90d', models.IntegerField(default=0)),
                ('late_payments_count', models.IntegerField(default=0)),
                ('package_downgrades_count', models.IntegerField(default=0)),
                ('avg_session_duration_minutes', models.FloatField(blank=True, null=True)),
                ('monthly_recurring_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Most recent prediction for customer')),
                ('confidence', models.FloatField(blank=True, help_text='Model confidence (0-1)', null=True)),
                ('actual_churned', models.BooleanField(blank=True, help_text='Did customer actually churn?', null=True)),
                ('churned_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to='users.clienth')),
                ('ml_model', models.ForeignKey(blank=True, help_text='ML model used for prediction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.mlmodel')),
            ],
            options={
                'verbose_name': 'Churn Prediction',
                'verbose_name_plural': 'Churn Predictions',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='RetentionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('auto_discount_20', 'Auto-Apply 20% Discount'), ('sms_discount_10', 'SMS with 10% Offer'), ('sms_reengagement', 'Re-engagement SMS'), ('manual_outreach', 'Manual Account Manager Outreach')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority_score', models.FloatField(help_text='Priority based on MRR and churn score')),
                ('monthly_recurring_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue_at_risk', models.DecimalField(decimal_places=2, help_text='Estimated revenue loss if churned', max_digits=10)),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('action_details', models.JSONField(default=dict, help_text='Details of action taken (SMS sent, discount applied, etc.)')),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('retained', 'Customer Retained'), ('churned', 'Customer Churned'), ('relocated', 'Customer Relocated'), ('no_response', 'No Response')], default='pending', max_length=20)),
                ('outcome_date', models.DateField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('automated', models.BooleanField(default=True, help_text='Was this action automated?')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Account manager assigned (for manual tasks)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('churn_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_tasks', to='finance.churnprediction')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_tasks', to='users.clienth')),
            ],
            options={
                'verbose_name': 'Retention Task',
                'verbose_name_plural': 'Retention Tasks',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='churnprediction',
            index=models.Index(fields=['customer', 'is_active'], name='finance_chu_custome_5b00d0_idx'),
        ),
        migrations.AddIndex(
            model_name='churnprediction',
            index=models.Index(fields=['risk_level', 'prediction_date'], name='finance_chu_risk_le_c28036_idx'),
        ),
        migrations.AddIndex(
            model_name='churnprediction',
            index=models.Index(fields=['churn_score'], name='finance_chu_churn_s_ba5225_idx'),
        ),
        migrations.AddIndex(
            model_name='retentiontask',
            index=models.Index(fields=['customer', 'status'], name='finance_ret_custome_5b0d30_idx'),
        ),
        migrations.AddIndex(
            model_name='retentiontask',
            index=models.Index(fields=['status', 'priority_score'], name='finance_ret_status_aaa34c_idx'),
        ),
        migrations.AddIndex(
            model_name='retentiontask',
            index=models.Index(fields=['outcome'], name='finance_ret_outcome_e1e8a3_idx'),
        ),
    ]
