# Generated by Django 5.2.12 on 2026-04-09 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_retentiontask_churn_prediction_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast_date', models.DateField(help_text='Date this forecast was generated')),
                ('forecast_type', models.CharField(choices=[('revenue', 'Revenue Forecast'), ('expense', 'Expense Forecast'), ('net_cash_flow', 'Net Cash Flow'), ('cash_position', 'Cash Position')], max_length=20)),
                ('scenario', models.CharField(choices=[('optimistic', 'Optimistic (P10)'), ('base', 'Base Case (P50)'), ('conservative', 'Conservative (P90)')], default='base', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('horizon_days', models.IntegerField(help_text='Forecast horizon in days (30/90/180)')),
                ('forecast_data', models.JSONField(help_text='Daily forecast values: [{date, value, lower_bound, upper_bound}]')),
                ('total_forecasted', models.DecimalField(decimal_places=2, help_text='Total forecasted amount for period', max_digits=15)),
                ('average_daily', models.DecimalField(decimal_places=2, help_text='Average daily amount', max_digits=15)),
                ('model_accuracy', models.FloatField(blank=True, help_text='Model accuracy on historical data (MAPE)', null=True)),
                ('confidence_interval', models.FloatField(default=0.95, help_text='Confidence interval (0.80, 0.95)')),
                ('training_data_size', models.IntegerField(help_text='Number of historical data points used')),
                ('training_period_days', models.IntegerField(default=365, help_text='Historical period used for training (days)')),
                ('has_weekly_seasonality', models.BooleanField(default=False)),
                ('has_monthly_seasonality', models.BooleanField(default=False)),
                ('has_yearly_seasonality', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Most recent forecast for this type/scenario')),
            ],
            options={
                'verbose_name': 'Cash Flow Forecast',
                'verbose_name_plural': 'Cash Flow Forecasts',
                'ordering': ['-forecast_date', 'forecast_type', 'scenario'],
                'indexes': [models.Index(fields=['forecast_date', 'forecast_type', 'scenario'], name='finance_cas_forecas_8afa90_idx'), models.Index(fields=['is_active', 'forecast_type'], name='finance_cas_is_acti_2700a7_idx'), models.Index(fields=['period_start', 'period_end'], name='finance_cas_period__046e68_idx')],
                'unique_together': {('forecast_date', 'forecast_type', 'scenario', 'horizon_days')},
            },
        ),
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('churn_score', models.FloatField(help_text='Churn probability (0-1)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('prediction_method', models.CharField(choices=[('rule_based', 'Rule-Based Model'), ('ml_model', 'Machine Learning Model'), ('hybrid', 'Hybrid (Rule + ML)')], default='rule_based', max_length=20)),
                ('risk_factors', models.JSONField(default=dict, help_text='Contributing factors with scores')),
                ('top_factors', models.JSONField(default=list, help_text='Top 3 factors driving churn risk')),
                ('days_since_last_session', models.IntegerField(blank=True, null=True)),
                ('support_tickets_90d', models.IntegerField(default=0)),
                ('late_payments_count', models.IntegerField(default=0)),
                ('package_downgrades_count', models.IntegerField(default=0)),
                ('avg_session_duration_minutes', models.FloatField(blank=True, null=True)),
                ('monthly_recurring_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Most recent prediction for customer')),
                ('confidence', models.FloatField(blank=True, help_text='Model confidence (0-1)', null=True)),
                ('actual_churned', models.BooleanField(blank=True, help_text='Did customer actually churn?', null=True)),
                ('churned_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to='users.clienth')),
                ('ml_model', models.ForeignKey(blank=True, help_text='ML model used for prediction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.mlmodel')),
            ],
            options={
                'verbose_name': 'Churn Prediction',
                'verbose_name_plural': 'Churn Predictions',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='RetentionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('auto_discount_20', 'Auto-Apply 20% Discount'), ('sms_discount_10', 'SMS with 10% Offer'), ('sms_reengagement', 'Re-engagement SMS'), ('manual_outreach', 'Manual Account Manager Outreach')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority_score', models.FloatField(help_text='Priority based on MRR and churn score')),
                ('monthly_recurring_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue_at_risk', models.DecimalField(decimal_places=2, help_text='Estimated revenue loss if churned', max_digits=10)),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('action_details', models.JSONField(default=dict, help_text='Details of action taken (SMS sent, discount applied, etc.)')),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('retained', 'Customer Retained'), ('churned', 'Customer Churned'), ('relocated', 'Customer Relocated'), ('no_response', 'No Response')], default='pending', max_length=20)),
                ('outcome_date', models.DateField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('automated', models.BooleanField(default=True, help_text='Was this action automated?')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Account manager assigned (for manual tasks)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('churn_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_tasks', to='finance.churnprediction')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_tasks', to='users.clienth')),
            ],
            options={
                'verbose_name': 'Retention Task',
                'verbose_name_plural': 'Retention Tasks',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('low_cash_position', 'Low Cash Position'), ('unusual_expense', 'Unusual Expense Forecast'), ('revenue_decline', 'Revenue Decline Forecast'), ('negative_cash_flow', 'Negative Cash Flow'), ('threshold_breach', 'Threshold Breach')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='active', max_length=20)),
                ('alert_date', models.DateField()),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recommended_action', models.TextField(blank=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='finance.cashflowforecast')),
            ],
            options={
                'verbose_name': 'Cash Flow Alert',
                'verbose_name_plural': 'Cash Flow Alerts',
                'ordering': ['-alert_date', '-severity'],
                'indexes': [models.Index(fields=['alert_type', 'status'], name='finance_cas_alert_t_027dd7_idx'), models.Index(fields=['severity', 'status'], name='finance_cas_severit_0c454e_idx'), models.Index(fields=['alert_date'], name='finance_cas_alert_d_96103c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='churnprediction',
            index=models.Index(fields=['customer', 'is_active'], name='finance_chu_custome_5b00d0_idx'),
        ),
        migrations.AddIndex(
            model_name='churnprediction',
            index=models.Index(fields=['risk_level', 'prediction_date'], name='finance_chu_risk_le_c28036_idx'),
        ),
        migrations.AddIndex(
            model_name='churnprediction',
            index=models.Index(fields=['churn_score'], name='finance_chu_churn_s_ba5225_idx'),
        ),
        migrations.AddIndex(
            model_name='retentiontask',
            index=models.Index(fields=['customer', 'status'], name='finance_ret_custome_5b0d30_idx'),
        ),
        migrations.AddIndex(
            model_name='retentiontask',
            index=models.Index(fields=['status', 'priority_score'], name='finance_ret_status_aaa34c_idx'),
        ),
        migrations.AddIndex(
            model_name='retentiontask',
            index=models.Index(fields=['outcome'], name='finance_ret_outcome_e1e8a3_idx'),
        ),
    ]
