# Generated by Django 5.2.12 on 2026-04-09 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_cashflowforecast_churnprediction_retentiontask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration', models.DurationField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_items', models.IntegerField(default=0)),
                ('matched_items', models.IntegerField(default=0)),
                ('unmatched_items', models.IntegerField(default=0)),
                ('review_items', models.IntegerField(default=0)),
                ('auto_match_rate', models.FloatField(blank=True, help_text='Percentage of items auto-matched', null=True)),
                ('average_confidence', models.FloatField(blank=True, help_text='Average confidence score', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation Job',
                'verbose_name_plural': 'Reconciliation Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_reference', models.CharField(max_length=200)),
                ('source_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source_date', models.DateField()),
                ('source_customer_info', models.CharField(blank=True, help_text='Customer name/phone from source', max_length=200)),
                ('source_description', models.TextField(blank=True)),
                ('match_action', models.CharField(choices=[('auto', 'Auto-Matched'), ('review', 'Needs Review'), ('manual', 'Manual Match'), ('rejected', 'Rejected')], default='review', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Overall confidence (0-1)')),
                ('amount_match_score', models.FloatField(help_text='Amount matching score (0-1)')),
                ('customer_match_score', models.FloatField(help_text='Customer matching score (0-1)')),
                ('date_match_score', models.FloatField(help_text='Date proximity score (0-1)')),
                ('match_factors', models.JSONField(default=dict, help_text='Detailed matching factors')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='finance.reconciliationjob')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_matches', to=settings.AUTH_USER_MODEL)),
                ('transaction_id_ref', models.CharField(blank=True, max_length=100, help_text='PaymentTransaction transaction_id reference')),
            ],
            options={
                'verbose_name': 'Reconciliation Match',
                'verbose_name_plural': 'Reconciliation Matches',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('amount_tolerance', 'Amount Tolerance'), ('date_range', 'Date Range'), ('customer_mapping', 'Customer Mapping'), ('auto_match_threshold', 'Auto-Match Threshold')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict, help_text='Rule-specific configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules applied first')),
                ('times_applied', models.IntegerField(default=0)),
                ('last_applied', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reconciliation Rule',
                'verbose_name_plural': 'Reconciliation Rules',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['rule_type', 'is_active'], name='finance_rec_rule_ty_4fbf21_idx'), models.Index(fields=['priority'], name='finance_rec_priorit_bf2cb7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reconciliationjob',
            index=models.Index(fields=['job_id'], name='finance_rec_job_id_64f767_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationjob',
            index=models.Index(fields=['status', 'created_at'], name='finance_rec_status_871a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['job', 'match_action'], name='finance_rec_job_id_600043_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['status', 'confidence_score'], name='finance_rec_status_693493_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['source_reference'], name='finance_rec_source__f5a6f5_idx'),
        ),
    ]
