# Generated by Django 5.2.12 on 2026-04-09 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_reconciliationjob_reconciliationmatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationmatch',
            name='transaction_id_ref',
            field=models.CharField(blank=True, help_text='Transaction ID reference', max_length=255),
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mrr_current', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mrr_last_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mrr_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mrr_growth_pct', models.FloatField(default=0)),
                ('active_customers', models.IntegerField(default=0)),
                ('active_customers_last_month', models.IntegerField(default=0)),
                ('churn_rate_30d', models.FloatField(default=0)),
                ('new_customers_30d', models.IntegerField(default=0)),
                ('cash_position', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_position_30d_ago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_receivables', models.JSONField(default=dict)),
                ('total_receivables', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('network_uptime_7d', models.FloatField(default=100.0)),
                ('revenue_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('high_risk_customers', models.IntegerField(default=0)),
                ('computed_in_ms', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='finance_kpi_timesta_c2d099_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True)),
                ('week_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('top_wins', models.JSONField(default=list)),
                ('top_risks', models.JSONField(default=list)),
                ('budget_status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('over_budget', 'Over Budget')], default='on_track', max_length=20)),
                ('budget_summary', models.JSONField(default=dict)),
                ('churn_risk_summary', models.JSONField(default=dict)),
                ('weekly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekly_new_customers', models.IntegerField(default=0)),
                ('weekly_churned_customers', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
        migrations.CreateModel(
            name='BoardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_month', models.DateField(db_index=True)),
                ('report_year', models.IntegerField()),
                ('financial_performance', models.JSONField(default=dict)),
                ('customer_metrics', models.JSONField(default=dict)),
                ('operational_metrics', models.JSONField(default=dict)),
                ('risk_register', models.JSONField(default=dict)),
                ('cash_flow_forecast', models.JSONField(default=dict)),
                ('executive_summary', models.TextField(blank=True)),
                ('key_highlights', models.JSONField(default=list)),
                ('challenges', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('distributed', 'Distributed')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('distributed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='board_reports/pdf/')),
                ('pptx_file', models.FileField(blank=True, null=True, upload_to='board_reports/pptx/')),
                ('generation_time_seconds', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_year', '-report_month'],
                'unique_together': {('report_year', 'report_month')},
            },
        ),
    ]
