# Generated by Django 5.2.12 on 2026-04-17 08:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_reconciliationmatch_transaction_id_ref_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('transaction_id_ref', models.CharField(blank=True, db_index=True, help_text='PaymentTransaction.transaction_id', max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('credited', 'Credited')], default='issued', max_length=20)),
                ('line_items', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/')),
                ('kra_pin_customer', models.CharField(blank=True, max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='users.clienth')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='finance_inv_custome_f7b372_idx'), models.Index(fields=['issue_date'], name='finance_inv_issue_d_3b7e1d_idx'), models.Index(fields=['invoice_number'], name='finance_inv_invoice_89da8a_idx')],
            },
        ),
    ]
