# Generated by Django 5.2.12 on 2026-04-17 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VATReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.IntegerField()),
                ('period_year', models.IntegerField()),
                ('output_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('input_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('filed', 'Filed with KRA'), ('paid', 'VAT Paid')], default='draft', max_length=20)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('kra_reference', models.CharField(blank=True, max_length=50)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_returns_calculated', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_returns_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'indexes': [models.Index(fields=['period_year', 'period_month'], name='finance_vat_period__82f12d_idx'), models.Index(fields=['status'], name='finance_vat_status_53fbcc_idx')],
                'unique_together': {('period_year', 'period_month')},
            },
        ),
    ]
