# Generated by Django 5.2.12 on 2026-04-17 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_vat_return'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.CharField(choices=[('expiry_3d', '3 Days Before Expiry'), ('expiry_1d', '1 Day Before Expiry'), ('expiry_day', 'Expiry Day'), ('overdue_3d', '3 Days Overdue'), ('overdue_7d', '7 Days Overdue — Final Warning')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (opted out)')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='users.clienth')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['customer', 'reminder_type'], name='finance_pay_custome_77a08b_idx'), models.Index(fields=['status', 'scheduled_at'], name='finance_pay_status_756423_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT (Value Added Tax)'), ('paye', 'PAYE (Pay As You Earn)'), ('wht', 'Withholding Tax'), ('income_tax', 'Corporate Income Tax'), ('nssf', 'NSSF Contributions'), ('nhif', 'NHIF Contributions')], max_length=20)),
                ('period_month', models.IntegerField(blank=True, null=True)),
                ('period_year', models.IntegerField()),
                ('period_label', models.CharField(max_length=30)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('penalties', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('due_date', models.DateField()),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calculated', 'Calculated'), ('filed', 'Filed'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('kra_reference', models.CharField(blank=True, max_length=50)),
                ('payment_slip', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_returns_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'indexes': [models.Index(fields=['tax_type', 'period_year', 'period_month'], name='finance_tax_tax_typ_e86dea_idx'), models.Index(fields=['status', 'due_date'], name='finance_tax_status_502702_idx')],
            },
        ),
    ]
