# Generated by Django 5.2.12 on 2026-04-17 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_credit_note_payroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('network_equipment', 'Network Equipment'), ('vehicles', 'Vehicles'), ('computers', 'Computers & IT'), ('furniture', 'Furniture & Fixtures'), ('buildings', 'Buildings'), ('land', 'Land'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('useful_life_years', models.IntegerField(help_text='Expected useful life in years')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('reducing_balance', 'Reducing Balance'), ('none', 'No Depreciation (Land)')], default='straight_line', max_length=20)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, help_text='Residual value at end of life', max_digits=14)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_book_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('disposal_notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.department')),
            ],
            options={
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['category', 'status'], name='finance_ass_categor_b5eb73_idx'), models.Index(fields=['department'], name='finance_ass_departm_3ecd59_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_pin', models.CharField(blank=True, max_length=20)),
                ('invoice_number', models.CharField(max_length=100)),
                ('our_reference', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('expense_category', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('approved', 'Approved'), ('scheduled', 'Payment Scheduled'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('overdue', 'Overdue')], default='received', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('wht_applicable', models.BooleanField(default=False)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendor_invoices', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.department')),
            ],
            options={
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='finance_ven_status_822236_idx'), models.Index(fields=['vendor_name'], name='finance_ven_vendor__07b568_idx')],
            },
        ),
    ]
