# Generated by Django 5.2.12 on 2026-04-17 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_asset_ap'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_credited', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ar_account', to='users.clienth')),
            ],
        ),
        migrations.CreateModel(
            name='DebtCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_overdue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('days_overdue', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved — Paid'), ('written_off', 'Written Off'), ('suspended', 'Service Suspended')], default='open', max_length=20)),
                ('escalation_level', models.CharField(choices=[('reminder', 'Payment Reminder'), ('warning', 'Formal Warning'), ('suspension', 'Service Suspension'), ('legal', 'Legal Action')], default='reminder', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_collections', to='users.clienth')),
                ('write_off_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_write_offs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount_overdue'],
                'indexes': [models.Index(fields=['status', 'days_overdue'], name='finance_deb_status_4adf41_idx'), models.Index(fields=['customer'], name='finance_deb_custome_413990_idx')],
            },
        ),
    ]
