# Generated by Django 5.2.12 on 2026-04-17 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_ar_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_label', models.CharField(max_length=50)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payroll_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('forex_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit_margin', models.FloatField(default=0)),
                ('expense_breakdown', models.JSONField(default=dict)),
                ('revenue_breakdown', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('period_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ForexGainLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_ref', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense in Foreign Currency'), ('payment', 'Payment Received in Foreign Currency'), ('invoice', 'Invoice in Foreign Currency')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exchange_rate_used', models.DecimalField(decimal_places=6, max_digits=15)),
                ('kes_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settlement_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('settlement_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_realized', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('original_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forex_originals', to='finance.currency')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_date', 'original_currency'], name='finance_for_transac_7a2321_idx'), models.Index(fields=['is_realized'], name='finance_for_is_real_327d01_idx')],
            },
        ),
    ]
