# Generated by Django 5.2.12 on 2026-04-17 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_pl_forex'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.CharField(choices=[('equity', 'Equity Bank'), ('kcb', 'KCB Bank'), ('coop', 'Co-op Bank'), ('mpesa', 'M-Pesa Statement'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='bank_statements/')),
                ('filename', models.CharField(max_length=255)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('reconciling', 'Reconciling'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('total_entries', models.IntegerField(default=0)),
                ('parsed_entries', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('matched_transaction_id', models.CharField(blank=True, max_length=255)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.bankstatement')),
            ],
            options={
                'ordering': ['transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_name', models.CharField(max_length=200)),
                ('package_code', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_day', models.IntegerField(default=1, help_text='Day of month to bill (1-28)')),
                ('next_billing_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('failed', 'Failed — Max Retries')], default='active', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_billed_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_billing', to='users.clienth')),
            ],
            options={
                'ordering': ['next_billing_date'],
                'indexes': [models.Index(fields=['status', 'next_billing_date'], name='finance_rec_status_2b2635_idx')],
            },
        ),
    ]
