# Generated by Django 5.2.12 on 2026-04-17 12:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_medium_features'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=100)),
                ('coverage_type', models.CharField(max_length=100)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='annual', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('assets_covered', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Standard SLA', max_length=100)),
                ('uptime_guarantee_pct', models.DecimalField(decimal_places=2, default=Decimal('99.5'), max_digits=5)),
                ('credit_pct_per_hour', models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text='% of monthly bill credited per hour of downtime', max_digits=5)),
                ('max_credit_pct', models.DecimalField(decimal_places=2, default=Decimal('30.0'), help_text='Maximum credit as % of monthly bill', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hq', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_hq', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CLVCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort_month', models.DateField(help_text='First month of customer acquisition')),
                ('cohort_size', models.IntegerField(default=0)),
                ('month_offset', models.IntegerField(help_text='Months since acquisition (0=first month)')),
                ('active_customers', models.IntegerField(default=0)),
                ('retention_rate', models.FloatField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_revenue_per_customer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cumulative_clv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['cohort_month', 'month_offset'],
                'unique_together': {('cohort_month', 'month_offset')},
            },
        ),
        migrations.CreateModel(
            name='DividendDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(max_length=50)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('distribution_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('wht_rate', models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('declared_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividend_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('credited', 'Credits Applied')], default='open', max_length=20)),
                ('credits_generated', models.IntegerField(default=0)),
                ('affected_customers', models.ManyToManyField(blank=True, related_name='outage_events', to='users.clienth')),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.slapolicy')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_auto', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='finance_pay_transac_2ab2b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_no', models.IntegerField()),
                ('due_date', models.DateField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='finance.investment')),
            ],
            options={
                'ordering': ['installment_no'],
                'unique_together': {('investment', 'installment_no')},
            },
        ),
    ]
