# Generated by Django 5.2.4 on 2026-01-27 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True, max_length=500)),
                ('ad_type', models.CharField(choices=[('banner', 'Banner Ad'), ('interstitial', 'Full Screen Ad'), ('popup', 'Popup Ad'), ('notification', 'Notification Ad'), ('video', 'Video Ad'), ('native', 'Native Content Ad'), ('carousel', 'Image Carousel Ad'), ('audio', 'Audio Ad')], default='banner', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('campaign_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Primary image for banner, popup, native, notification ads', null=True, upload_to='ads/images/%Y/%m/%d/')),
                ('video_file', models.FileField(blank=True, help_text='Video file for video ads (MP4, WebM)', null=True, upload_to='ads/videos/%Y/%m/%d/')),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Thumbnail for video ads', null=True, upload_to='ads/thumbnails/%Y/%m/%d/')),
                ('video_duration', models.DurationField(blank=True, help_text='Duration of video ad', null=True)),
                ('audio_file', models.FileField(blank=True, help_text='Audio file for audio ads (MP3, WAV)', null=True, upload_to='ads/audio/%Y/%m/%d/')),
                ('audio_duration', models.DurationField(blank=True, help_text='Duration of audio ad', null=True)),
                ('carousel_images', models.JSONField(default=list, help_text='List of image URLs/paths for carousel ads')),
                ('content', models.TextField(blank=True, help_text='HTML/content for native ads')),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='ads/logos/%Y/%m/%d/')),
                ('cta_text', models.CharField(default='Learn More', max_length=50)),
                ('cta_url', models.URLField(blank=True)),
                ('cta_color', models.CharField(default='#007bff', max_length=7)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('new', 'New Users'), ('returning', 'Returning Users'), ('premium', 'Premium Users')], default='all', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bidding_strategy', models.CharField(choices=[('cpc', 'Cost Per Click'), ('cpm', 'Cost Per 1000 Impressions'), ('fixed', 'Fixed Cost')], default='cpc', max_length=20)),
                ('cost_per_click', models.DecimalField(decimal_places=4, default=0.5, max_digits=8)),
                ('cost_per_impression', models.DecimalField(decimal_places=4, default=0.02, max_digits=8)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('campaign_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('locations', models.ManyToManyField(related_name='advertisements', to='locations.location')),
            ],
            options={
                'db_table': 'advertisements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ads/media/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20)),
                ('format', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('duration', models.DurationField(blank=True, help_text='For video/audio files', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='ads.advertisement')),
            ],
            options={
                'db_table': 'ad_media',
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='advertiseme_status_802f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['ad_type', 'is_active'], name='advertiseme_ad_type_a2499f_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['campaign_id'], name='advertiseme_campaig_d72800_idx'),
        ),
    ]
