# Generated by Django 5.2.4 on 2026-02-02 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('hotspot_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('is_captive_portal', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_path', models.CharField(max_length=200)),
                ('request_method', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'network_detection_logs',
                'indexes': [models.Index(fields=['client_ip', 'detected_at'], name='network_det_client__3a9a0a_idx'), models.Index(fields=['session_fingerprint'], name='network_det_session_da7d6b_idx'), models.Index(fields=['detected_at'], name='network_det_detecte_a485f0_idx')],
            },
        ),
    ]
