# Generated by Django 5.2.4 on 2025-08-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypass',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailypass',
            name='limit',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='dailypass',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailypass',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('soldout', 'Soldout')], default='soldout', max_length=20, null=True),
        ),
    ]
