# Generated by Django 5.2.4 on 2025-08-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailypass_end_date_dailypass_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypass',
            name='banner',
            field=models.CharField(choices=[('NEW', 'New'), ('HOT', 'HOT')], default='NEW', max_length=20, null=True),
        ),
    ]
