# Generated by Django 5.2.4 on 2025-08-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienth',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
