# Generated by Django 5.2.4 on 2026-01-27 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('packages', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('email', 'Email Template'), ('sms', 'SMS Template'), ('push', 'Push Template'), ('in_app', 'In-App Template'), ('pusher', 'Pusher Template'), ('alert', 'Alert Template')], max_length=10)),
                ('notification_type', models.CharField(choices=[('system', 'System Notification'), ('billing', 'Billing & Payment'), ('security', 'Security Alert'), ('promotional', 'Promotional'), ('maintenance', 'Maintenance Alert'), ('usage', 'Usage Alert'), ('voucher', 'Voucher Notification'), ('roaming', 'Roaming Notification'), ('package_expiry', 'Package Expiry'), ('low_balance', 'Low Balance Alert'), ('data_exhausted', 'Data Exhausted')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Email subject or push title', max_length=255)),
                ('message_template', models.TextField(help_text='Template with {{ variables }}')),
                ('short_template', models.TextField(blank=True, help_text='Short version for SMS/push')),
                ('pusher_template', models.JSONField(default=dict, help_text='Pusher message structure')),
                ('is_active', models.BooleanField(default=True)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('default_channels', models.JSONField(default=list)),
                ('default_persistent', models.BooleanField(default=True)),
                ('default_auto_dismiss', models.IntegerField(blank=True, null=True)),
                ('default_icon', models.CharField(blank=True, max_length=50)),
                ('default_badge', models.CharField(blank=True, max_length=20)),
                ('available_variables', models.JSONField(default=list, help_text='List of available template variables')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'indexes': [models.Index(fields=['template_type'], name='notificatio_templat_5e0a58_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_d9e94e_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_b2a982_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('user', 'User Specific'), ('client', 'Client Specific'), ('global', 'Global')], default='user', max_length=10)),
                ('is_broadcast', models.BooleanField(default=False, help_text='Send to multiple users')),
                ('target_audience', models.JSONField(default=list, help_text='Target specific user segments')),
                ('notification_type', models.CharField(choices=[('system', 'System Notification'), ('billing', 'Billing & Payment'), ('security', 'Security Alert'), ('promotional', 'Promotional'), ('maintenance', 'Maintenance Alert'), ('usage', 'Usage Alert'), ('voucher', 'Voucher Notification'), ('roaming', 'Roaming Notification'), ('package_expiry', 'Package Expiry'), ('low_balance', 'Low Balance Alert'), ('data_exhausted', 'Data Exhausted')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('short_message', models.CharField(blank=True, help_text='Short version for SMS/push', max_length=160)),
                ('is_persistent', models.BooleanField(default=True, help_text='Stay in notifications until manually dismissed')),
                ('auto_dismiss_seconds', models.IntegerField(blank=True, help_text='Auto dismiss after X seconds (for alerts)', null=True)),
                ('pusher_channel', models.CharField(blank=True, help_text='Pusher channel name', max_length=100)),
                ('pusher_event', models.CharField(blank=True, help_text='Pusher event name', max_length=100)),
                ('channels', models.JSONField(default=list, help_text='List of channels to deliver through')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Schedule for future delivery', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expiration', null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('in_app_delivered', models.BooleanField(default=False)),
                ('pusher_sent', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, help_text='URL for action button')),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=50)),
                ('context_data', models.JSONField(default=dict, help_text='Additional context data')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('client_context', models.JSONField(default=dict, help_text='Client-specific data like location, package, etc.')),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI display', max_length=50)),
                ('badge', models.CharField(blank=True, help_text='Badge text/count', max_length=20)),
                ('vibration_pattern', models.JSONField(default=list, help_text='Vibration pattern for mobile')),
                ('source', models.CharField(default='system', help_text='Source system/module', max_length=100)),
                ('template_id', models.CharField(blank=True, help_text='Template identifier', max_length=100)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_notifications', to='users.clienth')),
                ('target_locations', models.ManyToManyField(blank=True, to='locations.location')),
                ('target_packages', models.ManyToManyField(blank=True, to='packages.packagetype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['client', 'created_at'], name='notificatio_client__891d00_idx'), models.Index(fields=['scope', 'created_at'], name='notificatio_scope_e0bb74_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'), models.Index(fields=['is_sent'], name='notificatio_is_sent_254da2_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx'), models.Index(fields=['scheduled_for'], name='notificatio_schedul_cf7340_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx'), models.Index(fields=['is_persistent'], name='notificatio_is_pers_1d6021_idx'), models.Index(fields=['is_broadcast'], name='notificatio_is_broa_b3a109_idx'), models.Index(fields=['pusher_sent'], name='notificatio_pusher__5c86af_idx')],
            },
        ),
    ]
