# Generated by Django 5.2.4 on 2025-11-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default='LOC-001', help_text='Location code like HQ-001', max_length=10, unique=True)),
                ('location_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('branch', 'Branch Office'), ('hotspot', 'Public Hotspot'), ('commercial', 'Commercial Building')], default='hotspot', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('coordinates', models.CharField(blank=True, max_length=100)),
                ('router_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nas_identifier', models.CharField(blank=True, max_length=100)),
                ('max_concurrent_users', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_roaming_in', models.BooleanField(default=True, help_text='Allow users from other locations to roam here')),
                ('allow_roaming_out', models.BooleanField(default=True, help_text='Allow users from this location to roam elsewhere')),
                ('roaming_price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for roaming users', max_digits=3)),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['name'],
            },
        ),
    ]
