# Generated by Django 4.2.28 on 2026-03-27 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('transaction_type', models.CharField(choices=[('balance_update', 'Balance Update'), ('voucher_purchase', 'Voucher Purchase'), ('roaming_activation', 'Roaming Activation'), ('user_registration', 'User Registration'), ('package_activation', 'Package Activation')], max_length=30)),
                ('state', models.CharField(choices=[('preparing', 'Preparing'), ('prepared', 'Prepared'), ('committing', 'Committing'), ('committed', 'Committed'), ('aborting', 'Aborting'), ('aborted', 'Aborted'), ('failed', 'Failed')], default='preparing', max_length=20)),
                ('transaction_data', models.JSONField(default=dict)),
                ('compensation_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('timeout_at', models.DateTimeField()),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'distributed_transactions',
            },
        ),
        migrations.CreateModel(
            name='LocationHealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('memory_usage_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('disk_usage_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('network_latency_ms', models.IntegerField(default=0)),
                ('bandwidth_utilization_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('packet_loss_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('active_sessions', models.IntegerField(default=0)),
                ('pending_transactions', models.IntegerField(default=0)),
                ('sync_lag_seconds', models.IntegerField(default=0)),
                ('error_rate_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('db_connection_count', models.IntegerField(default=0)),
                ('db_query_avg_time_ms', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'location_health_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationMesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('connection_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'), ('failed', 'Failed')], default='good', max_length=20)),
                ('latency_ms', models.IntegerField(default=0)),
                ('bandwidth_mbps', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('packet_loss_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('can_sync_users', models.BooleanField(default=True)),
                ('can_sync_transactions', models.BooleanField(default=True)),
                ('can_sync_vouchers', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='Priority for peer selection (1=highest)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Mesh Connection',
                'verbose_name_plural': 'Location Mesh Connections',
                'db_table': 'location_mesh',
            },
        ),
        migrations.CreateModel(
            name='NodeIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('central', 'Central Server'), ('location', 'Location Server')], max_length=20)),
                ('node_id', models.CharField(max_length=50, unique=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('registration_token', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('current_mode', models.CharField(choices=[('online', 'Online - Full Connectivity'), ('degraded', 'Degraded - Limited Connectivity'), ('offline', 'Offline - Local Operation Only'), ('emergency', 'Emergency - Critical Functions Only')], default='online', max_length=20)),
                ('last_mode_change', models.DateTimeField(auto_now=True)),
                ('central_api_url', models.URLField(blank=True)),
                ('central_connection_status', models.BooleanField(default=True)),
                ('last_central_contact', models.DateTimeField(blank=True, null=True)),
                ('sync_lag_seconds', models.IntegerField(default=0)),
                ('pending_transactions', models.IntegerField(default=0)),
                ('error_rate_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('circuit_breaker_state', models.CharField(choices=[('closed', 'Closed - Normal Operation'), ('open', 'Open - Failing Fast'), ('half_open', 'Half Open - Testing Recovery')], default='closed', max_length=20)),
                ('circuit_breaker_failure_count', models.IntegerField(default=0)),
                ('circuit_breaker_last_failure', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Node Identity',
                'verbose_name_plural': 'Node Identities',
                'db_table': 'node_identity',
            },
        ),
        migrations.CreateModel(
            name='TransactionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('committed', 'Committed'), ('aborted', 'Aborted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction_participants',
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='bandwidth_limit_mbps',
            field=models.IntegerField(default=100, help_text='Total bandwidth limit in Mbps'),
        ),
        migrations.AddField(
            model_name='location',
            name='central_api_url',
            field=models.URLField(blank=True, help_text='Central server API URL for sync'),
        ),
        migrations.AddField(
            model_name='location',
            name='current_user_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='health_check_interval',
            field=models.IntegerField(default=60, help_text='Health check interval in seconds'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_central',
            field=models.BooleanField(default=False, help_text='Is this the central coordination server?'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_online',
            field=models.BooleanField(default=True, help_text='Current connectivity status'),
        ),
        migrations.AddField(
            model_name='location',
            name='last_seen_online',
            field=models.DateTimeField(blank=True, help_text='Last successful communication with this location', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='maintenance_message',
            field=models.TextField(blank=True, help_text='Message to display during maintenance'),
        ),
        migrations.AddField(
            model_name='location',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Is location in maintenance mode?'),
        ),
        migrations.AddField(
            model_name='location',
            name='max_roaming_locations',
            field=models.IntegerField(default=3, help_text='Maximum locations a user can roam to simultaneously'),
        ),
        migrations.AddField(
            model_name='location',
            name='node_id',
            field=models.CharField(blank=True, help_text='Unique node identifier: central, nairobi, mombasa', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='offline_credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum credit allowed during offline operation', max_digits=10),
        ),
        migrations.AddField(
            model_name='location',
            name='offline_operation_enabled',
            field=models.BooleanField(default=True, help_text='Allow offline operation when central is unreachable'),
        ),
        migrations.AddField(
            model_name='location',
            name='priority',
            field=models.IntegerField(default=1, help_text='Location priority for load balancing (1=highest)'),
        ),
        migrations.AddField(
            model_name='location',
            name='roaming_time_restrictions',
            field=models.JSONField(default=dict, help_text='Time-based roaming restrictions'),
        ),
        migrations.AddField(
            model_name='location',
            name='router_config',
            field=models.JSONField(default=dict, help_text='RouterOS connection configuration'),
        ),
        migrations.AddField(
            model_name='location',
            name='sync_api_key',
            field=models.CharField(blank=True, help_text='API key for authenticating with central server', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='roaming_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for roaming users (1.0 = same price, 1.2 = 20% surcharge)', max_digits=3),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['node_id'], name='locations_node_id_ec609a_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_central'], name='locations_is_cent_c79384_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_online'], name='locations_is_onli_9400d2_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['last_seen_online'], name='locations_last_se_754cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_active', 'maintenance_mode'], name='locations_is_acti_e2693c_idx'),
        ),
        migrations.AddField(
            model_name='transactionparticipant',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='transactionparticipant',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='locations.distributedtransaction'),
        ),
        migrations.AddField(
            model_name='nodeidentity',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Associated location (null for central server)', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationmesh',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesh_connections', to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationmesh',
            name='peer_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_connections', to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationhealthmetrics',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='locations.location'),
        ),
        migrations.AddField(
            model_name='distributedtransaction',
            name='coordinator_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_transactions', to='locations.location'),
        ),
        migrations.AddField(
            model_name='distributedtransaction',
            name='participant_locations',
            field=models.ManyToManyField(related_name='participated_transactions', through='locations.TransactionParticipant', to='locations.location'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionparticipant',
            unique_together={('transaction', 'location')},
        ),
        migrations.AddIndex(
            model_name='locationmesh',
            index=models.Index(fields=['location', 'is_connected'], name='location_me_locatio_574eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='locationmesh',
            index=models.Index(fields=['connection_quality'], name='location_me_connect_2012fe_idx'),
        ),
        migrations.AddIndex(
            model_name='locationmesh',
            index=models.Index(fields=['priority'], name='location_me_priorit_30ccc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationmesh',
            unique_together={('location', 'peer_location')},
        ),
        migrations.AddIndex(
            model_name='locationhealthmetrics',
            index=models.Index(fields=['location', 'recorded_at'], name='location_he_locatio_a2f91a_idx'),
        ),
        migrations.AddIndex(
            model_name='locationhealthmetrics',
            index=models.Index(fields=['recorded_at'], name='location_he_recorde_72ef1e_idx'),
        ),
        migrations.AddIndex(
            model_name='distributedtransaction',
            index=models.Index(fields=['state'], name='distributed_state_e13a97_idx'),
        ),
        migrations.AddIndex(
            model_name='distributedtransaction',
            index=models.Index(fields=['transaction_type'], name='distributed_transac_a544e2_idx'),
        ),
        migrations.AddIndex(
            model_name='distributedtransaction',
            index=models.Index(fields=['started_at'], name='distributed_started_6a2139_idx'),
        ),
        migrations.AddIndex(
            model_name='distributedtransaction',
            index=models.Index(fields=['timeout_at'], name='distributed_timeout_c58913_idx'),
        ),
    ]
