tunnel: e0261038-4629-4917-a7de-3f617c934afb
credentials-file: /etc/cloudflared/e0261038-4629-4917-a7de-3f617c934afb.json

ingress:
  - hostname: teralinkxwaves.uk
    service: http://nginx:80

  - hostname: cli.teralinkxwaves.uk
    service: http://nginx:80

  - hostname: srv.teralinkxwaves.uk
    service: http://nginx:80

  - hostname: su.teralinkxwaves.uk
    service: http://nginx:80

  - hostname: router.teralinkxwaves.uk
    service: http://nginx:80

  - hostname: radius.teralinkxwaves.uk
    service: http://nginx:80

  - hostname: mt.teralinkxwaves.uk
    service: http://nginx:80

  - hostname: prom.teralinkxwaves.uk
    service: http://nginx:80

  - hostname: sec.teralinkxwaves.uk
    service: http://nginx:80

  - hostname: lab.teralinkxwaves.uk
    service: http://nginx:80

  - service: http_status:404
