#config.yml
tunnel: 1fb40a2f-56df-4268-b480-fad4fc059f22
credentials-file: /etc/cloudflared/1fb40a2f-56df-4268-b480-fad4fc059f22.json

# ingress:
#   - hostname: teralinkxwaves.uk
#     service: http://nginx:80
#   - service: http_status:404

ingress:
  - hostname: test.teralinkxwaves.uk
    service: http://web:8009
  - service: http_status:404
