# Generated by Django 5.2.4 on 2026-01-27 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.CharField(help_text='Unique client account identifier', max_length=15, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='User-friendly display name', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20)),
                ('account_tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='basic', help_text='Service tier determining features and limits', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive'), ('banned', 'Banned')], default='active', help_text='Current account status', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current account balance', max_digits=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit allowance', max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Lifetime total spending', max_digits=15)),
                ('lifetime_data_used', models.BigIntegerField(default=0, help_text='Total data consumed in bytes')),
                ('last_location_update', models.DateTimeField(blank=True, help_text='When location was last updated', null=True)),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Count of consecutive failed login attempts')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled for this account')),
                ('auto_renew', models.BooleanField(default=False, help_text='Auto-renew packages when expired')),
                ('active_voucher', models.CharField(blank=True, help_text='Currently active voucher code', max_length=50)),
                ('voucher_expiry', models.DateTimeField(blank=True, help_text='Expiration time of active voucher', null=True)),
                ('last_login', models.DateTimeField(auto_now=True, help_text='Last login time across all devices')),
                ('last_balance_update', models.DateTimeField(auto_now=True, help_text='When balance was last updated')),
                ('profile_image', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_images/')),
                ('current_location', models.ForeignKey(blank=True, help_text='Current active location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='locations.location')),
                ('home_location', models.ForeignKey(help_text='Primary registered location', on_delete=django.db.models.deletion.PROTECT, related_name='home_users', to='locations.location')),
                ('user', models.OneToOneField(help_text='Django User account linked to this client', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mac_address', models.CharField(db_index=True, help_text='Unique hardware MAC address', max_length=17)),
                ('device_name', models.CharField(help_text='User-friendly device name', max_length=100)),
                ('device_type', models.CharField(choices=[('phone', 'Smartphone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('iot', 'IoT Device'), ('gaming', 'Gaming Console'), ('tv', 'Smart TV'), ('other', 'Other')], default='other', help_text='Type of device', max_length=20)),
                ('device_platform', models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'iOS'), ('other', 'Other OS')], default='other', help_text='Operating system platform', max_length=20)),
                ('device_model', models.CharField(blank=True, help_text='Device model information', max_length=100)),
                ('device_manufacturer', models.CharField(blank=True, help_text='Device manufacturer', max_length=100)),
                ('is_trusted', models.BooleanField(default=False, help_text='Whether device is trusted for auto-connection')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='Current device status', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time device was seen online', null=True)),
                ('total_connections', models.IntegerField(default=0, help_text='Total number of connections made')),
                ('previous_owners', models.JSONField(blank=True, default=list, help_text="History of previous owners [{'user_id': X, 'from': 'date', 'to': 'date'}]")),
                ('device_identification', models.JSONField(blank=True, default=dict, help_text='Additional device identification (browser, OS version, etc.)')),
                ('auto_connect', models.BooleanField(default=True, help_text='Automatically connect when in range')),
                ('max_concurrent_sessions', models.IntegerField(default=1, help_text='Maximum concurrent sessions allowed')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the device was first created/registered', null=True)),
                ('favorite_location', models.ForeignKey(blank=True, help_text='Most frequently used location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_devices', to='locations.location')),
                ('last_seen_location', models.ForeignKey(blank=True, help_text='Last known location of device', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('user', models.ForeignKey(help_text='Client account that owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.clienth')),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Current IP address for this session')),
                ('login_time', models.DateTimeField(auto_now_add=True, help_text='When the session started')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the session is currently active')),
                ('session_type', models.CharField(choices=[('web', 'Web Authentication'), ('network', 'Network Connection'), ('voucher', 'Voucher Active')], default='network', help_text='Type of session', max_length=20)),
                ('is_owner', models.BooleanField(default=True, help_text='Is this user the device owner? (False for borrowed devices)')),
                ('was_transferred', models.BooleanField(default=False, help_text='Was device transferred during this session?')),
                ('request_metadata', models.JSONField(blank=True, default=dict, help_text='Additional request metadata')),
                ('active_voucher', models.CharField(blank=True, help_text='Active voucher code for this session', max_length=50)),
                ('voucher_activated', models.DateTimeField(blank=True, help_text='When voucher was activated for this session', null=True)),
                ('voucher_expires', models.DateTimeField(blank=True, help_text='When active voucher expires', null=True)),
                ('auto_logout_minutes', models.IntegerField(default=1440, help_text='Auto logout after X minutes (0 = never)')),
                ('data_used', models.BigIntegerField(default=0, help_text='Data used during this session (bytes)')),
                ('user_agent', models.TextField(blank=True, default='', help_text='User agent string from the connection')),
                ('device', models.ForeignKey(help_text='Device associated with this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.userdevice')),
                ('location', models.ForeignKey(help_text='Current location for this session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('user', models.ForeignKey(help_text='Client account for this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.clienth')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='clienth',
            index=models.Index(fields=['account'], name='users_clien_account_62d0de_idx'),
        ),
        migrations.AddIndex(
            model_name='clienth',
            index=models.Index(fields=['status'], name='users_clien_status_4ff604_idx'),
        ),
        migrations.AddIndex(
            model_name='clienth',
            index=models.Index(fields=['account_tier'], name='users_clien_account_d57f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='clienth',
            index=models.Index(fields=['home_location'], name='users_clien_home_lo_91a8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='clienth',
            index=models.Index(fields=['current_location'], name='users_clien_current_3e0122_idx'),
        ),
        migrations.AddIndex(
            model_name='clienth',
            index=models.Index(fields=['balance'], name='users_clien_balance_8faffb_idx'),
        ),
        migrations.AddIndex(
            model_name='clienth',
            index=models.Index(fields=['last_login'], name='users_clien_last_lo_761c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'status'], name='users_userd_user_id_f41038_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['mac_address'], name='users_userd_mac_add_ce386c_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['last_seen'], name='users_userd_last_se_b90b98_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_type'], name='users_userd_device__43a80e_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_platform'], name='users_userd_device__2c35ac_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['favorite_location'], name='users_userd_favorit_2eaa97_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['is_trusted'], name='users_userd_is_trus_03504b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('mac_address', 'user'), name='unique_device_per_user'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='users_users_user_id_3887fe_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['device', 'is_active'], name='users_users_device__a64bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='users_users_session_924804_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['login_time'], name='users_users_login_t_4b988a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='users_users_last_ac_62f4a2_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active'], name='users_users_is_acti_8d4729_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_type'], name='users_users_session_fea54c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_owner'], name='users_users_is_owne_dcf708_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['active_voucher'], name='users_users_active__59eecd_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['voucher_expires'], name='users_users_voucher_815f5e_idx'),
        ),
    ]
